keys:
  - &users:
    - &jjszaniszlo age1hn6n2s09yctejlxaa3nkzcw35ylgwrrj5urj025akyqkgfn62ylqprxns8
  - &hosts:
    - &athena age15frld9vk6kv84mkcmp9jl292jljvmsuuwat6n3rzx5m4w9zn6cfsd590dh

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *jjszaniszlo
      - *athena
