keys:
  - &users:
    - &jjszaniszlo age10nxp0x73psf4nxv78xyf8vzg62lanyzzmpt7r8vx7ru9erg2cecss5k396
  - &hosts:
    - &athena age1nj8hzsqrsmqvcc95xjrs9eweem2c5rvg2w0lzgn85ehu8ku5yctszn7833

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *jjszaniszlo
      - *athena
